In [117]:
import numpy as np
import pandas as pd

import matplotlib
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from scipy.cluster.hierarchy import dendrogram, linkage, fcluster
from sklearn.cluster import DBSCAN
matplotlib.style.use('ggplot')
%matplotlib inline

In [118]:
data = pd.read_csv("digit.dat", sep=";")

#Удаляем лишние столбцы
data.pop("A")
data.pop("A2")
data.pop("B2")
data.pop("C2")
data.pop("D2")
data.pop("E2")
data.pop("F2")
data.pop("G2")
data.pop("H2")

#Заменяем строки на числа
data.replace("ZERO", 0, inplace=True)
data.replace("zero", 0, inplace=True)
data.replace("ONE", 1, inplace=True)
data.replace("one", 1, inplace=True)
data.replace("two", 2, inplace=True)
data.replace("three", 3, inplace=True)
data.replace("four", 4, inplace=True)
data.replace("five", 5, inplace=True)
data.replace("six", 6, inplace=True)
data.replace("seven", 7, inplace=True)
data.replace("eight", 8, inplace=True)
data.replace("nine", 9, inplace=True)

data.head()

B  C  D  E  F  G  H
0  1  0  1  0  0  1  0
1  0  0  1  0  0  1  0
2  0  1  1  1  0  1  0
3  1  1  1  1  1  0  0
4  0  1  1  1  1  1  1

In [110]:
dbscan = DBSCAN(eps=0.5, metric='euclidean', min_samples=5)
dbscan.fit(data)

DBSCAN()

In [111]:
unique, counts = np.unique(dbscan.labels_, return_counts=True)
print(np.asarray((unique, counts)).T)
3#Слишком много кластеров и выбрасов

[[ -1 110]
 [  0  24]
 [  1  18]
 [  2  26]
 [  3  35]
 [  4   5]
 [  5  24]
 [  6  42]
 [  7   8]
 [  8  36]
 [  9  29]
 [ 10   5]
 [ 11  11]
 [ 12   5]
 [ 13   7]
 [ 14  25]
 [ 15   5]
 [ 16  31]
 [ 17   6]
 [ 18  10]
 [ 19   6]
 [ 20   8]
 [ 21   5]
 [ 22   8]
 [ 23   5]
 [ 24   6]]


3

In [135]:
#Переберём min_samples
for i in range(1, 30):
    for j in np.arange(0.01, 2, 0.01):
        dbscan = DBSCAN(eps=j, metric='euclidean', min_samples=i)
        dbscan.fit(data)

        unique, counts = np.unique(dbscan.labels_, return_counts=True)
        if len(np.asarray((unique, counts)).T) > 3 and len(np.asarray((unique, counts)).T) < 8: print(np.asarray((unique, counts)).T, i, j)
#Основываясь на предыдущих квастерных анализах попробуем взять случай с min_samples=26, где 6 кластеров

[[ -1 301]
 [  0  26]
 [  1  35]
 [  2  42]
 [  3  36]
 [  4  29]
 [  5  31]] 26 0.01
[[ -1 301]
 [  0  26]
 [  1  35]
 [  2  42]
 [  3  36]
 [  4  29]
 [  5  31]] 26 0.02
[[ -1 301]
 [  0  26]
 [  1  35]
 [  2  42]
 [  3  36]
 [  4  29]
 [  5  31]] 26 0.03
[[ -1 301]
 [  0  26]
 [  1  35]
 [  2  42]
 [  3  36]
 [  4  29]
 [  5  31]] 26 0.04
[[ -1 301]
 [  0  26]
 [  1  35]
 [  2  42]
 [  3  36]
 [  4  29]
 [  5  31]] 26 0.05
[[ -1 301]
 [  0  26]
 [  1  35]
 [  2  42]
 [  3  36]
 [  4  29]
 [  5  31]] 26 0.060000000000000005
[[ -1 301]
 [  0  26]
 [  1  35]
 [  2  42]
 [  3  36]
 [  4  29]
 [  5  31]] 26 0.06999999999999999
[[ -1 301]
 [  0  26]
 [  1  35]
 [  2  42]
 [  3  36]
 [  4  29]
 [  5  31]] 26 0.08
[[ -1 301]
 [  0  26]
 [  1  35]
 [  2  42]
 [  3  36]
 [  4  29]
 [  5  31]] 26 0.09
[[ -1 301]
 [  0  26]
 [  1  35]
 [  2  42]
 [  3  36]
 [  4  29]
 [  5  31]] 26 0.09999999999999999
[[ -1 301]
 [  0  26]
 [  1  35]
 [  2  42]
 [  3  36]
 [  4  29]
 [  5  31]] 26 0.11
[[ -1 30

[[ -1 301]
 [  0  26]
 [  1  35]
 [  2  42]
 [  3  36]
 [  4  29]
 [  5  31]] 26 0.99
[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 [  4  31]] 27 0.01
[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 [  4  31]] 27 0.02
[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 [  4  31]] 27 0.03
[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 [  4  31]] 27 0.04
[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 [  4  31]] 27 0.05
[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 [  4  31]] 27 0.060000000000000005
[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 [  4  31]] 27 0.06999999999999999
[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 [  4  31]] 27 0.08
[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 [  4  31]] 27 0.09
[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 [  4  31]] 27 0.09999999999999999
[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 [  4  31]] 27 0.11
[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]

[[ -1  72]
 [  0 255]
 [  1  35]
 [  2  42]
 [  3  36]
 [  4  29]
 [  5  31]] 27 1.06
[[ -1  72]
 [  0 255]
 [  1  35]
 [  2  42]
 [  3  36]
 [  4  29]
 [  5  31]] 27 1.07
[[ -1  72]
 [  0 255]
 [  1  35]
 [  2  42]
 [  3  36]
 [  4  29]
 [  5  31]] 27 1.08
[[ -1  72]
 [  0 255]
 [  1  35]
 [  2  42]
 [  3  36]
 [  4  29]
 [  5  31]] 27 1.09
[[ -1  72]
 [  0 255]
 [  1  35]
 [  2  42]
 [  3  36]
 [  4  29]
 [  5  31]] 27 1.1
[[ -1  72]
 [  0 255]
 [  1  35]
 [  2  42]
 [  3  36]
 [  4  29]
 [  5  31]] 27 1.11
[[ -1  72]
 [  0 255]
 [  1  35]
 [  2  42]
 [  3  36]
 [  4  29]
 [  5  31]] 27 1.12
[[ -1  72]
 [  0 255]
 [  1  35]
 [  2  42]
 [  3  36]
 [  4  29]
 [  5  31]] 27 1.1300000000000001
[[ -1  72]
 [  0 255]
 [  1  35]
 [  2  42]
 [  3  36]
 [  4  29]
 [  5  31]] 27 1.1400000000000001
[[ -1  72]
 [  0 255]
 [  1  35]
 [  2  42]
 [  3  36]
 [  4  29]
 [  5  31]] 27 1.1500000000000001
[[ -1  72]
 [  0 255]
 [  1  35]
 [  2  42]
 [  3  36]
 [  4  29]
 [  5  31]] 27 1.1600000000000001

[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 [  4  31]] 28 0.8400000000000001
[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 [  4  31]] 28 0.85
[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 [  4  31]] 28 0.86
[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 [  4  31]] 28 0.87
[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 [  4  31]] 28 0.88
[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 [  4  31]] 28 0.89
[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 [  4  31]] 28 0.9
[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 [  4  31]] 28 0.91
[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 [  4  31]] 28 0.92
[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 [  4  31]] 28 0.93
[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 [  4  31]] 28 0.9400000000000001
[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 [  4  31]] 28 0.9500000000000001
[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 [  

[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 [  4  31]] 29 0.42000000000000004
[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 [  4  31]] 29 0.43
[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 [  4  31]] 29 0.44
[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 [  4  31]] 29 0.45
[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 [  4  31]] 29 0.46
[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 [  4  31]] 29 0.47000000000000003
[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 [  4  31]] 29 0.48000000000000004
[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 [  4  31]] 29 0.49
[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 [  4  31]] 29 0.5
[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 [  4  31]] 29 0.51
[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 [  4  31]] 29 0.52
[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 [  4  31]] 29 0.53
[[ -1 327]
 [  0  35]
 [  1  42]
 [  2  36]
 [  3  29]
 

In [132]:
#Зафиксируем min_samples 26 и поперебираем eps
for i in np.arange(0.01, 2, 0.01):
    dbscan = DBSCAN(eps=i, metric='euclidean', min_samples=26)
    dbscan.fit(data)

    unique, counts = np.unique(dbscan.labels_, return_counts=True)
    print(np.asarray((unique, counts)).T, i)
#Заметим, что при eps > 1.41 резко меняется число кластеров на 3, а при остальных случаях вообще ничего не меняется, оставим eps=0.5

[[ -1 301]
 [  0  26]
 [  1  35]
 [  2  42]
 [  3  36]
 [  4  29]
 [  5  31]] 0.01
[[ -1 301]
 [  0  26]
 [  1  35]
 [  2  42]
 [  3  36]
 [  4  29]
 [  5  31]] 0.02
[[ -1 301]
 [  0  26]
 [  1  35]
 [  2  42]
 [  3  36]
 [  4  29]
 [  5  31]] 0.03
[[ -1 301]
 [  0  26]
 [  1  35]
 [  2  42]
 [  3  36]
 [  4  29]
 [  5  31]] 0.04
[[ -1 301]
 [  0  26]
 [  1  35]
 [  2  42]
 [  3  36]
 [  4  29]
 [  5  31]] 0.05
[[ -1 301]
 [  0  26]
 [  1  35]
 [  2  42]
 [  3  36]
 [  4  29]
 [  5  31]] 0.060000000000000005
[[ -1 301]
 [  0  26]
 [  1  35]
 [  2  42]
 [  3  36]
 [  4  29]
 [  5  31]] 0.06999999999999999
[[ -1 301]
 [  0  26]
 [  1  35]
 [  2  42]
 [  3  36]
 [  4  29]
 [  5  31]] 0.08
[[ -1 301]
 [  0  26]
 [  1  35]
 [  2  42]
 [  3  36]
 [  4  29]
 [  5  31]] 0.09
[[ -1 301]
 [  0  26]
 [  1  35]
 [  2  42]
 [  3  36]
 [  4  29]
 [  5  31]] 0.09999999999999999
[[ -1 301]
 [  0  26]
 [  1  35]
 [  2  42]
 [  3  36]
 [  4  29]
 [  5  31]] 0.11
[[ -1 301]
 [  0  26]
 [  1  35]
 [  2  4

[[ -1  33]
 [  0 268]
 [  1  26]
 [  2  35]
 [  3  42]
 [  4  36]
 [  5  29]
 [  6  31]] 1.1500000000000001
[[ -1  33]
 [  0 268]
 [  1  26]
 [  2  35]
 [  3  42]
 [  4  36]
 [  5  29]
 [  6  31]] 1.1600000000000001
[[ -1  33]
 [  0 268]
 [  1  26]
 [  2  35]
 [  3  42]
 [  4  36]
 [  5  29]
 [  6  31]] 1.17
[[ -1  33]
 [  0 268]
 [  1  26]
 [  2  35]
 [  3  42]
 [  4  36]
 [  5  29]
 [  6  31]] 1.18
[[ -1  33]
 [  0 268]
 [  1  26]
 [  2  35]
 [  3  42]
 [  4  36]
 [  5  29]
 [  6  31]] 1.19
[[ -1  33]
 [  0 268]
 [  1  26]
 [  2  35]
 [  3  42]
 [  4  36]
 [  5  29]
 [  6  31]] 1.2
[[ -1  33]
 [  0 268]
 [  1  26]
 [  2  35]
 [  3  42]
 [  4  36]
 [  5  29]
 [  6  31]] 1.21
[[ -1  33]
 [  0 268]
 [  1  26]
 [  2  35]
 [  3  42]
 [  4  36]
 [  5  29]
 [  6  31]] 1.22
[[ -1  33]
 [  0 268]
 [  1  26]
 [  2  35]
 [  3  42]
 [  4  36]
 [  5  29]
 [  6  31]] 1.23
[[ -1  33]
 [  0 268]
 [  1  26]
 [  2  35]
 [  3  42]
 [  4  36]
 [  5  29]
 [  6  31]] 1.24
[[ -1  33]
 [  0 268]
 [  1  26]


In [133]:
#Проинтерпретируем
dbscan = DBSCAN(eps=0.5, metric='euclidean', min_samples=26)
dbscan.fit(data)

unique, counts = np.unique(dbscan.labels_, return_counts=True)
print(np.asarray((unique, counts)).T, i)

data['dbscan'] = dbscan.labels_
data.groupby('dbscan').mean()
#Кластер 0 - цифра 
#Кластер 1 - цифра 5
#Кластер 2 - цифра 9
#Кластер 3 - цифра 8
#Кластер 4 - цифра 6
#Кластер 5 - цифра 3

[[ -1 301]
 [  0  26]
 [  1  35]
 [  2  42]
 [  3  36]
 [  4  29]
 [  5  31]] 1.99


B         C         D        E         F        G         H
dbscan                                                                    
-1      0.671096  0.435216  0.757475  0.54485  0.481728  0.72093  0.534884
 0      0.000000  1.000000  1.000000  1.00000  0.000000  1.00000  0.000000
 1      1.000000  1.000000  0.000000  1.00000  0.000000  1.00000  1.000000
 2      1.000000  1.000000  1.000000  1.00000  0.000000  1.00000  1.000000
 3      1.000000  1.000000  1.000000  1.00000  1.000000  1.00000  1.000000
 4      1.000000  1.000000  0.000000  1.00000  1.000000  1.00000  1.000000
 5      1.000000  0.000000  1.000000  1.00000  0.000000  1.00000  1.000000